---
type: zero-touch

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: '>_Terminal-01'
    path: /wetty
    port: 443
  - name: "MCP-{guid} terminal"
    url: /wetty_mcp-{guid}/ssh/lab-user

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Infinicorp Overview"
      solveButton: false
    - name: module-02
      label: "Verify Connectivity"
      solveButton: false
    - name: module-03
      label: "Creating a Content Repository"
      scripts: [solve, validation]
      solveButton: true
    - name: module-04
      label: "AgnosticV Configuration"
      scripts: [solve, validation]
      solveButton: true
    - name: module-05
      label: "UI Configuration"
      scripts: [solve, validation]
      solveButton: true
    - name: module-06
      label: "User Data and Variables"
      scripts: [solve, validation]
      solveButton: true
    - name: module-07
      label: "Attribute Injection Example"
      scripts: [solve, validation]
      solveButton: true
    - name: module-08
      label: "OCP4 Role Reference"
      scripts: [solve, validation]
      solveButton: true
    - name: module-09
      label: "VM Role Reference"
      scripts: [solve, validation]
      solveButton: true
    - name: module-10
      label: "Architecture"
      scripts: [solve, validation]
      solveButton: true
    - name: module-11
      label: "Showroom Deployer"
      scripts: [solve, validation]
      solveButton: true
    - name: module-12
      label: "Showroom Images"
      scripts: [solve, validation]
      solveButton: true
    - name: module-13
      label: "Nookbag UI"
      scripts: [solve, validation]
      solveButton: true
    - name: module-14
      label: "OCP Integration"
      scripts: [solve, validation]
      solveButton: true
    - name: module-15
      label: "Contributing"
      scripts: [solve, validation]
      solveButton: true
