---
type: zero-touch

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: '>_Terminal-01'
    path: /wetty
    port: 443
  - name: 'Satellite'
    url: "https://satellite-{{ subdomain }}"

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Module 1"
      scripts: [solve, validation]
      solveButton: true
    - name: module-02
      label: "Module 2"
      scripts: [solve, validation]
      solveButton: true
