:imagesdir: ../images

= Verifying connectivity to the MCP Agents 
To start out your experience with Infinicorp, we need to validate that the setup is working properly.

This module will get you into goose, validate that the mcp servers are connected, and run a couple of test prompts.

*Expand a section below to complete the tasks in that section.* +  
*Please complete each section in order.*

=====
.Start Goose
[%collapsible]
====
You will be using the MCP Server Terminal for most of these exercises. 
You should see that in the showroom on the right pane beside these instructions. 

Goose also has a user interface, but you’ll be using the CLI. 

Your system name is: `mcp-{guid}` +

NOTE: Hosts in your environment all contain {guid}. In a shared environment like the inventory at console.redhat.com, you might see similar named hosts, but this unique identifier is for your systems.  

In the MCP terminal window, start a tmux session by running: 

[source,bash,run]
----
tmux
----

Then, start a goose session by running: 

[source,bash,run]
----
goose session
----

This will start the goose session 

NOTE: Without running tmux the environment will appear to enter strange spaces if you are manually typing commands. + 
That is to be expected.  +
Running tmux first gives a smoother expereince for the lab - this isn't something you would need to do outside of Infinicorp's virtual environment that was provisioned for you.

====
=====


=====
.Verify MCP Server connectivity
[%collapsible]
====

With Goose started, the next thing you should do is verify that the various MCP servers are connected.  You have 3 different MCP servers installed on the same host, so we need to check that they are all connected.  
As a reminder, the three MCP servers are:

* Red Hat Lightspeed (formerly known as Red Hat Insights) MCP
* Red Hat Satellite MCP
* Red Hat Enterprise Linux MCP

Make sure you are in the goose session, and run the following prompt:
[source,bash,run]
----
List the available tools and MCP servers you are currently connected to.
----

The output will include a variety of MCP extensions and tools. 
Review the output and make sure that you see the following listed: 
NOTE: You may need to scroll up to see the output like the above image. The lightspeedmcp server contains individual servers for several different services like Advisor and Inventory.  This prompt will also give information about these servers.

====
=====


=====
.Query Hybrid Cloud Console inventory
[%collapsible]
====

Goose says you’re connected, but to be completely sure, you should run a prompt to verify.  Start with asking how many systems are connected to Red Hat Lightspeed at the Hybrid Cloud Console (also known as console.redhat.com) by running the following prompt:

[source,bash,run]
----
How many systems are connected to Red Hat Lightspeed? 
----
NOTE: The number of systems you see in the response will be different from the image above.  This is expected.

The returned result is the number of systems connected to Red Hat Lightspeed.
This confirms that Goose is able to communicate with the APIs over at the Hybrid Cloud Console using the Red Hat Lightspeed MCP server..

====
=====

=====
.Query Satellite inventory
[%collapsible]
====

Now to check the Satellite MCP server, ask Goose what systems are connected to the Satellite.

[source,bash,run]
----
What hosts are connected to my Satellite? 
----

The results will list the servers connected to your Satellite.  
Unlike the Hybrid Cloud Console inventory which is shared, the Satellite inventory is a private environment - you will not see other people’s systems and you will only see your two hosts.

This confirms that Goose is able to communicate with your Satellite server using the Satellite MCP server.

=====
.Query RHEL specifics
[%collapsible]
====

The RHEL MCP server looks in more detail at specific systems - to test it out you’ll need to ask about a specific RHEL system.

[source,bash,run]
----
Check the current CPU load and memory usage for rhel-{guid}-1 
----

This will return basic information about CPU type and utilization along with memory utilization. 

This confirms that Goose is able to communicate with your RHEL hosts using the RHEL MCP server.

====
=====


=====
.Access to Hybrid Cloud Console and Satellite UI
[%collapsible]
====
The primary interface for this lab will be the mcp host with the goose terminal. 
You do not need to access the Hybrid Cloud Console or the Satellite UI for any reason in this lab. 

However - we know you may want to do so. 
The credentials are shared at the bottom of each module for convenience. 

**Hybrid Cloud Console**

Use a web browser to navigate to the https://console.redhat.com[Hybrid Cloud Console^] <-- Click to open in a new tab. +
Log into the Hybrid Cloud Console with the following credentials: +

User:
[source,sh,role=execute]
----
 rhpd-lightspeed-lb1305
----

Password:
[source,sh,role=execute]
----
rhdp*lightspeed2026!
----

**Satellite**

To log into the Satellite UI, use a web browser to navigate to the https://satellite-{guid}.apps.ocpvdev01.rhdp.net[Satellite UI^].

To log in, you’ll need the following credentials to log into the Satellite Web UI.

You can copy and paste each of them below.

[source,js]
----
admin
----

[source,js]
----
{satellite_password}
----

Now click `+Log In+`.


====
=====


After running this series of checks you now know that the various MCP servers are working in your environment and you’re ready to dig in a little deeper. 

Continue to the next module.
